# -*- coding: utf-8 -*-
"""Nonoka Shell —— 插件化桌面工具箱外壳包。"""

from .brand import (
    APP_NAME, APP_ID, PUBLISHER, VERSION, THEME_PRIMARY, THEME_PRIMARY_DARK,
    THEME_PRIMARY_SOFT, WINDOW_TITLE, WINDOW_WIDTH, WINDOW_HEIGHT,
    WINDOW_MIN_WIDTH, WINDOW_MIN_HEIGHT, DATA_DIR_NAME, CONFIG_FILE, LOG_FILE,
    LOG_DIR, COMPONENTS_DIR, REPO_URL, UPDATE_API,
)

__all__ = [
    "APP_NAME", "APP_ID", "PUBLISHER", "VERSION", "THEME_PRIMARY",
    "THEME_PRIMARY_DARK", "THEME_PRIMARY_SOFT", "WINDOW_TITLE", "WINDOW_WIDTH",
    "WINDOW_HEIGHT", "WINDOW_MIN_WIDTH", "WINDOW_MIN_HEIGHT", "DATA_DIR_NAME",
    "CONFIG_FILE", "LOG_FILE", "LOG_DIR", "COMPONENTS_DIR", "REPO_URL",
    "UPDATE_API",
]
